- name: Configure VM
  vars_prompt:
    - name: user_db
      prompt: what is your user db ?
      private: no
    - name: pwd_db
      prompt: what is your password db ?
      private: no
    - name: name_db
      prompt: what is db name ?
      private: no
  hosts: mouny-vm
  remote_user: mouny
  tasks:
    - name: Install pip
      become: yes
      apt:
        name: python-pip
        update_cache: yes
    - name: Install pip3
      become: yes
      apt:
        name: python3-pip
        update_cache: yes
        state: latest
    - name: Install modules with pip3
      pip:
        name:
          - psycopg2-binary
          - Flask
          - python-dotenv
        executable: pip3
    - name: Remove all element
      ansible.builtin.shell: rm -rf SFA
      args:
        executable: /bin/bash
    - name: Clone a repo
      ansible.builtin.git:
        repo: https://github.com/keomouny/SFA.git
        dest: /home/mouny/SFA
    - name: Create file .env
      copy:
        dest: /home/mouny/SFA/.env
        content: |
          POSTGRES_HOST="mouny-db.postgres.database.azure.com"
          POSTGRES_USER="{{user_db}}"
          POSTGRES_DBNAME="{{name_db}}"
          POSTGRES_PASSWORD="{{pwd_db}}"
    - name: modify file setup_logger.py
      copy:
        dest: /home/mouny/SFA/setup_logger.py
        content: |
          import logging
          logging.basicConfig(filename="SFA/logs/log.log",filemode="a",format="%(asctime)s - %(levelname)-8s - %(message)s", datefmt="%d/%m/%Y %H:%M:%S", level=logging.DEBUG)
          logger = logging.getLogger(__name__)
    - name: execute script main.py
      command: python3 /home/mouny/SFA/main.py
